// constants/evmDApps.ts
import { DAppInfo } from 'types/browser';

export const EVM_DAPPS: DAppInfo[] = [
  {
    id: '1',
    title: 'Uniswap V4',
    subtitle: 'Decentralized Exchange',
    url: 'https://app.uniswap.org',
    description: 'Swap, earn, and build on the leading decentralized crypto trading protocol.',
    categories: ['Exchange', 'DeFi'],
    chain: ['Ethereum'],
    is_featured: true,
    is_evm: true,
    is_substrate: false,
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/7083.png',
    preview_image: 'https://img.phemex.com/wp-content/uploads/2020/12/16072921/what-is-uniswap--1024x576.png',
    desktop_mode: false,
  },
  {
    id: '2',
    title: 'Aave V1',
    subtitle: 'Lend and Borrow',
    url: 'https://app.aave.com',
    description: 'Decentralized finance protocol for lending and borrowing.',
    categories: ['Lending', 'DeFi'],
    chain: ['Ethereum', 'Polygon'],
    is_featured: true,
    is_evm: true,
    is_substrate: false,
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/7278.png',
    preview_image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYGdWpRGzcbQLaPGHRp_GtXLLxpDkzaBdOwg&s',
    desktop_mode: true,
  },
  {
    id: '3',
    title: 'Compound',
    subtitle: 'Interest earning DeFi',
    url: 'https://compound.finance',
    description: 'Algorithmic protocol for lending and borrowing crypto assets.',
    categories: ['Lending', 'DeFi'],
    chain: ['Ethereum'],
    is_featured: true,
    is_evm: true,
    is_substrate: false,
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5692.png',
    preview_image: 'https://fxlmwpmedia.s3.amazonaws.com/wp-content/uploads/2023/07/26152920/2022-ARTICLE-IMAGE-6.png',
    desktop_mode: true,
  },
  {
    id: '4',
    title: 'Curve',
    subtitle: 'Stablecoin DEX',
    url: 'https://curve.fi',
    description: 'DEX optimized for stablecoin and wrapped token swaps.',
    categories: ['DeFi', 'Exchange'],
    chain: ['Ethereum'],
    is_featured: true,
    is_evm: true,
    is_substrate: false,
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/6538.png',
    preview_image: 'https://cdn.decrypt.co/resize/1024/height/512/wp-content/uploads/2023/05/curve-finance-defi-gID_7.jpg',
    desktop_mode: true,
  },
  {
    id: '5',
    title: 'SushiSwap',
    subtitle: 'Community DEX',
    url: 'https://sushi.com',
    description: 'Multi-chain DEX with staking, lending, and launchpad features.',
    categories: ['Exchange', 'DeFi'],
    chain: ['Ethereum', 'Polygon', 'Arbitrum'],
    is_featured: true,
    is_evm: true,
    is_substrate: false,
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/6758.png',
    preview_image: 'https://cdn.sushi.com/image/upload/v1731498183/sushi-assets/embed-web-visuals/default.jpg',
    desktop_mode: true,
  },
  {
    id: '6',
    title: 'Balancer',
    subtitle: 'Automated Portfolio Manager',
    url: 'https://balancer.fi/',
    description: 'DEX and automated portfolio management protocol.',
    categories: ['DeFi'],
    chain: ['Ethereum'],
    is_featured: false,
    is_evm: true,
    is_substrate: false,
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5728.png',
    preview_image: 'https://img.phemex.com/wp-content/uploads/2021/07/27025401/Balancer-Pools-1024x576.jpg',
    desktop_mode: true,
  },
  {
    id: '7',
    title: 'Lido',
    subtitle: 'Liquid ETH staking',
    url: 'https://stake.lido.fi',
    description: 'Stake your ETH and receive stETH while earning rewards.',
    categories: ['Staking'],
    chain: ['Ethereum'],
    is_featured: true,
    is_evm: true,
    is_substrate: false,
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/8000.png',
    preview_image: 'https://cdn.prod.website-files.com/67ed326db9d26b1dc1df7929/68017f5a2d3ed3df47abb82c_6793bce88ddde84c8e4c12ab_-1737732375631.webp',
    desktop_mode: true,
  },
  {
    id: '8',
    title: 'OpenSea',
    subtitle: 'NFT Marketplace',
    url: 'https://opensea.io',
    description: 'Buy, sell, and mint NFTs across multiple Ethereum networks.',
    categories: ['NFT'],
    chain: ['Ethereum', 'Polygon'],
    is_featured: true,
    is_evm: true,
    is_substrate: false,
    icon: 'https://storage.googleapis.com/opensea-static/Logomark/Logomark-Blue.png',
    preview_image: 'https://dreamfarmstudios.com/wp-content/uploads/2022/01/opensea3-800x425.jpg',
    desktop_mode: true,
  },
  {
    id: '9',
    title: 'Zerion',
    subtitle: 'DeFi Dashboard',
    url: 'https://app.zerion.io',
    description: 'Track, trade, and manage your DeFi assets in one place.',
    categories: ['Portfolio', 'Utility'],
    chain: ['Ethereum'],
    is_featured: false,
    is_evm: true,
    is_substrate: false,
    icon: '',
    preview_image: 'https://zerion.io/blog/content/images/max/1200/1-bA_YIYs7kCnV8TM0IgmbYg.jpeg',
    desktop_mode: true,
  },
  {
    id: '10',
    title: '1inch',
    subtitle: 'DEX Aggregator',
    url: 'https://app.1inch.io',
    description: 'Find the best token prices across all major DEXes.',
    categories: ['Aggregator', 'DeFi'],
    chain: ['Ethereum'],
    is_featured: true,
    is_evm: true,
    is_substrate: false,
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/8104.png',
    preview_image: 'https://blog.1inch.io/content/images/2024/10/1-25.png',
    desktop_mode: true,
  },
  {
    id: '11',
    title: 'Yearn Finance',
    subtitle: 'Yield Optimization',
    url: 'https://yearn.finance',
    description: 'Vaults that automatically earn the best yield on your crypto.',
    categories: ['Yield', 'DeFi'],
    chain: ['Ethereum'],
    is_featured: false,
    is_evm: true,
    is_substrate: false,
    icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5864.png',
    preview_image: 'https://blog.bingx.com/wp-content/uploads/2021/08/YFI-BLOG-2-01-1024x576.png',
    desktop_mode: true,
  },
];

export const EVM_DAPP_CATEGORIES = [
  { key: 'all', title: 'All' },
  { key: 'Exchange', title: 'Exchange' },
  { key: 'DeFi', title: 'DeFi' },
  { key: 'Lending', title: 'Lending' },
  { key: 'Staking', title: 'Staking' },
  { key: 'NFT', title: 'NFT' },
  { key: 'Portfolio', title: 'Portfolio' },
  { key: 'Utility', title: 'Utility' },
  { key: 'Aggregator', title: 'Aggregator' },
  { key: 'Yield', title: 'Yield' },
];
