// constants/evmDApps.ts
import { DAppInfo } from 'types/browser';

export const EVM_DAPPS: DAppInfo[] = [
  {
    id: '1',
    title: 'Uniswap V4',
    subtitle: 'Decentralized Exchange',
    url: 'https://app.uniswap.org',
    description: 'Swap, earn, and build on the leading decentralized crypto trading protocol.',
    categories: ['Exchange', 'DeFi'],
    chain: ['Ethereum'],
    is_featured: true,
    is_evm: true,
    is_substrate: false,
    icon: 'https://cryptologos.cc/logos/uniswap-uni-logo.png',
    preview_image: '',
    desktop_mode: false,
  },
  {
    id: '2',
    title: 'Aave V1',
    subtitle: 'Lend and Borrow',
    url: 'https://app.aave.com',
    description: 'Decentralized finance protocol for lending and borrowing.',
    categories: ['Lending', 'DeFi'],
    chain: ['Ethereum', 'Polygon'],
    is_featured: true,
    is_evm: true,
    is_substrate: false,
    icon: 'https://cryptologos.cc/logos/aave-aave-logo.png',
    preview_image: '',
    desktop_mode: true,
  },
  {
    id: '3',
    title: 'Compound',
    subtitle: 'Interest earning DeFi',
    url: 'https://compound.finance',
    description: 'Algorithmic protocol for lending and borrowing crypto assets.',
    categories: ['Lending', 'DeFi'],
    chain: ['Ethereum'],
    is_featured: true,
    is_evm: true,
    is_substrate: false,
    icon: 'https://cryptologos.cc/logos/compound-comp-logo.png',
    preview_image: '',
    desktop_mode: true,
  },
  {
    id: '4',
    title: 'Curve',
    subtitle: 'Stablecoin DEX',
    url: 'https://curve.fi',
    description: 'DEX optimized for stablecoin and wrapped token swaps.',
    categories: ['DeFi', 'Exchange'],
    chain: ['Ethereum'],
    is_featured: true,
    is_evm: true,
    is_substrate: false,
    icon: 'https://cryptologos.cc/logos/curve-dao-token-crv-logo.png',
    preview_image: '',
    desktop_mode: true,
  },
  {
    id: '5',
    title: 'SushiSwap',
    subtitle: 'Community DEX',
    url: 'https://sushi.com',
    description: 'Multi-chain DEX with staking, lending, and launchpad features.',
    categories: ['Exchange', 'DeFi'],
    chain: ['Ethereum', 'Polygon', 'Arbitrum'],
    is_featured: true,
    is_evm: true,
    is_substrate: false,
    icon: 'https://cryptologos.cc/logos/sushiswap-sushi-logo.png',
    preview_image: '',
    desktop_mode: true,
  },
  {
    id: '6',
    title: 'Balancer',
    subtitle: 'Automated Portfolio Manager',
    url: 'https://balancer.fi/',
    description: 'DEX and automated portfolio management protocol.',
    categories: ['DeFi'],
    chain: ['Ethereum'],
    is_featured: false,
    is_evm: true,
    is_substrate: false,
    icon: 'https://cryptologos.cc/logos/balancer-bal-logo.png',
    preview_image: '',
    desktop_mode: true,
  },
  {
    id: '7',
    title: 'Lido',
    subtitle: 'Liquid ETH staking',
    url: 'https://stake.lido.fi',
    description: 'Stake your ETH and receive stETH while earning rewards.',
    categories: ['Staking'],
    chain: ['Ethereum'],
    is_featured: true,
    is_evm: true,
    is_substrate: false,
    icon: 'https://cryptologos.cc/logos/lido-dao-token-ldo-logo.png',
    preview_image: '',
    desktop_mode: true,
  },
  {
    id: '8',
    title: 'OpenSea',
    subtitle: 'NFT Marketplace',
    url: 'https://opensea.io',
    description: 'Buy, sell, and mint NFTs across multiple Ethereum networks.',
    categories: ['NFT'],
    chain: ['Ethereum', 'Polygon'],
    is_featured: true,
    is_evm: true,
    is_substrate: false,
    icon: 'https://cryptologos.cc/logos/opensea-opensea-logo.png',
    preview_image: '',
    desktop_mode: true,
  },
  {
    id: '9',
    title: 'Zerion',
    subtitle: 'DeFi Dashboard',
    url: 'https://app.zerion.io',
    description: 'Track, trade, and manage your DeFi assets in one place.',
    categories: ['Portfolio', 'Utility'],
    chain: ['Ethereum'],
    is_featured: false,
    is_evm: true,
    is_substrate: false,
    icon: 'https://cryptologos.cc/logos/zerion-logo.png',
    preview_image: '',
    desktop_mode: true,
  },
  {
    id: '10',
    title: '1inch',
    subtitle: 'DEX Aggregator',
    url: 'https://app.1inch.io',
    description: 'Find the best token prices across all major DEXes.',
    categories: ['Aggregator', 'DeFi'],
    chain: ['Ethereum'],
    is_featured: true,
    is_evm: true,
    is_substrate: false,
    icon: 'https://cryptologos.cc/logos/1inch-1inch-logo.png',
    preview_image: '',
    desktop_mode: true,
  },
  {
    id: '11',
    title: 'Yearn Finance',
    subtitle: 'Yield Optimization',
    url: 'https://yearn.finance',
    description: 'Vaults that automatically earn the best yield on your crypto.',
    categories: ['Yield', 'DeFi'],
    chain: ['Ethereum'],
    is_featured: false,
    is_evm: true,
    is_substrate: false,
    icon: 'https://cryptologos.cc/logos/yearn-finance-yfi-logo.png',
    preview_image: '',
    desktop_mode: true,
  },
];
